### ISSUE TITLE
Plugin appears horribly broken

### ISSUE THREAD

**Issue by clayreimann** [nebula-plugins/gradle-contacts-plugin#7]
I've got this in my `build.gradle` and I'm seeing this output:

```
plugins {
    id "idea"
    id "java"
    id "antlr"
    id "jacoco"
    id "checkstyle"

    id 'nebula.project' version '3.0.4'
    id 'nebula.contacts' version '3.0.1'
...
contacts {
    'clayreimann@yahoo-inc.com' {
        name 'Clay Reimann'
    }
}
```

```
<developers>
    <developer>
      <email>Clay Reimann</email>
    </developer>
    <developer>
      <email>name</email>
    </developer>
    <developer>
      <email>clayreimann@yahoo-inc.com</email>
    </developer>
  </developers>
```

**Comment by nadavc** [comment]
I think `name` has been changed to `moniker` (based on [this](https://github.com/nebula-plugins/gradle-contacts-plugin/blob/master/src/main/groovy/nebula/plugin/contacts/Contact.groovy#L16) comment). Can you please check?

**Comment by clayreimann** [comment]
Moniker partially resolves things.
```gradle
contacts {
    "clayreimann@yahoo-inc.com" {
        moniker "Clay Reimann"
    }
}
```
produces:
```xml
  <developers>
    <developer>
      <name>Clay Reimann</name>
      <email>clayreimann@yahoo-inc.com</email>
    </developer>
  </developers>
```

However this:
```gradle
contacts {
    "clayreimann@yahoo-inc.com" {
        moniker "Clay Reimann"
        email "clayreimann@yahoo-inc.com"
    }
}
```
yields:
```xml
<developers>
    <developer>
      <name>Clay Reimann</name>
      <email>clayreimann@yahoo-inc.com</email>
    </developer>
    <developer>
      <email>email</email>
    </developer>
  </developers>
```

and 

```gradle
contacts {
    "clay" {
        moniker "Clay Reimann"
        email "clayreimann@yahoo-inc.com"
    }
}
```
yields:
```xml
<developers>
    <developer>
      <email>clayreimann@yahoo-inc.com</email>
    </developer>
    <developer>
      <email>email</email>
    </developer>
    <developer>
      <name>Clay Reimann</name>
      <email>clay</email>
    </developer>
  </developers>
```

**Comment by clayreimann** [comment]
At the least the `README` should be updated to reflect the `moniker` to `name` change.

**Comment by nadavc** [comment]
I reviewed the current code and updated the docs accordingly. Thanks again for the bug report!

**Comment by Nikecow** [comment]
The attribute "id" is also mentioned on the github page once, but it seems to be deprecated. Any reason for this? It seems like "moniker" is used for the full name, so "id" could be used for the nickname.

**Comment by DanielThomas** [comment]
@Nikecow I've fixed that reference. `id` was used interchangeably for GitHub and Twitter ids. There are now separate fields for those.

**Comment by Nikecow** [comment]
@DanielThomas Ok I see. I read that "name" was protected, so you went with moniker instead. Why don't you use "fullname" for example, and leave moniker for nicknames?
